theme = "catppuccin_mocha"

[keys.normal.space]
# lazygit
g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all"
]

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-inlay-hints = true
