theme = "base16_transchild"

[editor]
shell = ["nu", "-c"]
color-modes = true
bufferline = "multiple"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
