[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.rust-analyzer]
config = { check = { command = "clippy", extraArgs = ["--", "-Wclippy::pedantic"] } }

[[language]]
name = "markdown"
language-servers = ["marksman", "codebook"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]

[[language]]
name = "c-sharp"
language-servers = ["omnisharp", "codebook"]
